### ISSUE TITLE
changing shares amount leads to "TypeError: failed to fetch"

### ISSUE THREAD

**Issue by jerryliangxia** [emmanuel-bob-ma-joey/financial_dashboard#25]
<img width="1512" alt="Screenshot 2024-03-31 at 1 51 35 AM" src="https://github.com/emmanuel-bob-ma-joey/financial_dashboard/assets/60997074/f7b27b28-5a02-4cd5-a9ba-48be0c4dbf8c">

Steps to replicate:
- Navigate to Portfolio tab
- Change the number of shares for any company stock

DoD:
- Changing shares does not lead to error pop-up

**Comment by emmanuel-bob-ma-joey** [comment]
The frontend was making a post request to an API endpoint that wasnt configured to handle CORS preflight requests. It is fixed now, thanks for pointing it out! 💖
